# 베이스 이미지 선택
FROM mariadb:latest

# 환경 변수 설정
ENV MYSQL_HOST=13.125.60.211
ENV MYSQL_PORT=3306 
ENV MYSQL_DATABASE=valve
ENV MYSQL_USER=root
ENV MYSQL_PASSWORD=l1A87VgsZOB6

# 포트 열기
EXPOSE 3306

# 컨테이너 실행 시 실행할 명령
CMD ["mysqld"]
